# Build and Deploy to Azure

name: webstore-cicd

on:
  push:
  
env:
  AZURE_WEBAPP_NAME: 'web-app5516'    

jobs:
  build:
    name: 'Build and Publish .NET Web App'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3      

      - name: 'Restore'
        run: dotnet restore

      - name: 'Build'
        run: dotnet build --configuration Release

      - name: 'Publish'
        run: dotnet publish --configuration Release -o ./webstore

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: webstore
          path: ./webstore

  deploy: 
    name: Deploy to Web App
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: webstore-prod

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with: 
          name: webstore

      - name: Deploy to Azure WebApp
        uses: Azure/webapps-deploy@v3.0.1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

  
